import type { Request, Response } from 'express';
import prisma from '../config/db.js';
import { getSalesAuth } from '../utils/salesAuth.js';
import { activityService } from '../services/activity.service.js';
import { getUsersForModule } from '../utils/userScope.js';
import {
  ATTENDANCE_STATUSES, ATTENDANCE_STATUS_LABELS, DEFAULT_STATUS,
  HISTORICAL_EDIT_WINDOW_DAYS,
  todayYmd, isYmd, ymdToDate, dateToYmd,
  checkWritable, resolveStatus, findApprovedLeave, isDenial,
  canSelfAttend, canViewTeamAttendance, canOverrideAttendance,
  isOverridden, overriddenDenial,
} from '../services/marketingAttendance.service.js';

/**
 * MK-003 — Marketing attendance.
 *
 * Every timestamp written here is generated by the SERVER. A client can ask to
 * check in, but never says when — otherwise anyone could back-date a check-in
 * to look punctual.
 */

const uid = (req: Request) => Number((req as any).userId);
const str = (v: unknown): string => (typeof v === 'string' ? v.trim() : '');
const intId = (v: unknown): number | null => {
  const n = Number(typeof v === 'string' ? v.trim() : v);
  return Number.isInteger(n) && n > 0 ? n : null;
};

const serialize = (r: any) => ({
  id: r.id,
  userId: r.user_id,
  date: dateToYmd(r.attendance_date),
  status: r.status,
  statusLabel: ATTENDANCE_STATUS_LABELS[r.status as keyof typeof ATTENDANCE_STATUS_LABELS] ?? r.status,
  checkIn: r.check_in,
  checkOut: r.check_out,
  notes: r.notes,
  leaveId: r.leave_id,
  overriddenBy: r.overridden_by,
  overriddenAt: r.overridden_at,
  overrideReason: r.override_reason,
  /** Distinguishes a real record from the virtual Absent default. */
  persisted: true,
});

/** The virtual default — a day with no row. Never written to the database. */
const virtualAbsent = (userId: number, date: string) => ({
  id: null,
  userId,
  date,
  status: DEFAULT_STATUS,
  statusLabel: ATTENDANCE_STATUS_LABELS[DEFAULT_STATUS],
  checkIn: null,
  checkOut: null,
  notes: null,
  leaveId: null,
  overriddenBy: null,
  overriddenAt: null,
  overrideReason: null,
  persisted: false,
});

// ─────────────────────────────────────────────────────────────────────────────
// GET /marketing/attendance/me?date=
// ─────────────────────────────────────────────────────────────────────────────
export const getMyAttendance = async (req: Request, res: Response): Promise<any> => {
  try {
    const ctx = await getSalesAuth(req);
    const today = todayYmd();
    const date = isYmd(req.query.date) ? String(req.query.date) : today;

    const row: any = await prisma.marketing_attendance.findUnique({
      where: { user_id_attendance_date: { user_id: ctx.userId, attendance_date: ymdToDate(date) } },
    });

    // Offered so the UI can show "On Leave" as an option only when it is real.
    const approvedLeave = await findApprovedLeave(ctx.userId, date);

    return res.json({
      success: true,
      today,
      date,
      statuses: ATTENDANCE_STATUSES.map((key) => ({ key, label: ATTENDANCE_STATUS_LABELS[key] })),
      canSelfAttend: canSelfAttend(ctx),
      canViewTeam: canViewTeamAttendance(ctx),
      canOverride: canOverrideAttendance(ctx),
      historicalEditWindowDays: HISTORICAL_EDIT_WINDOW_DAYS,
      approvedLeave: approvedLeave ? { id: approvedLeave.id, leaveType: approvedLeave.leave_type } : null,
      attendance: row ? serialize(row) : virtualAbsent(ctx.userId, date),
    });
  } catch (error) {
    console.error('Error loading attendance:', error);
    return res.status(500).json({ error: 'Failed to load your attendance' });
  }
};

// ─────────────────────────────────────────────────────────────────────────────
// POST /marketing/attendance/check-in
// ─────────────────────────────────────────────────────────────────────────────
export const checkIn = async (req: Request, res: Response): Promise<any> => {
  try {
    const ctx = await getSalesAuth(req);
    const today = todayYmd();

    // Self-service is today-only; the date is not accepted from the client.
    const denial = checkWritable(ctx, ctx.userId, today, { isOverride: false });
    if (denial) return res.status(denial.status).json({ error: denial.message });

    const day = ymdToDate(today);
    const existing: any = await prisma.marketing_attendance.findUnique({
      where: { user_id_attendance_date: { user_id: ctx.userId, attendance_date: day } },
    });
    if (existing?.check_in) {
      return res.status(409).json({ error: 'You have already checked in today.', attendance: serialize(existing) });
    }
    /* P2-1 — a manager override OWNS the status for that day. Without this the
     * upsert below would write status:'present' over the override while leaving
     * overridden_by/override_reason in place, producing a row that contradicts
     * itself. See the invariant in marketingAttendance.service. */
    if (isOverridden(existing)) {
      const d = overriddenDenial();
      return res.status(d.status).json({ error: d.message, attendance: serialize(existing) });
    }

    // The SERVER stamps the time. Nothing from the body is used.
    const now = new Date();
    let row: any;
    try {
      row = await prisma.marketing_attendance.upsert({
        where: { user_id_attendance_date: { user_id: ctx.userId, attendance_date: day } },
        // Only ever fills a MISSING check-in — an existing one is rejected above,
        // and the unique key means a double-click resolves to one row.
        update: { check_in: now, status: 'present' },
        create: { user_id: ctx.userId, attendance_date: day, check_in: now, status: 'present' },
      });
    } catch (err) {
      // Lost the upsert race: the other request created the row microseconds
      // earlier. Report the existing record rather than a 500.
      const again: any = await prisma.marketing_attendance.findUnique({
        where: { user_id_attendance_date: { user_id: ctx.userId, attendance_date: day } },
      });
      if (again) return res.status(409).json({ error: 'You have already checked in today.', attendance: serialize(again) });
      throw err;
    }

    await activityService.logActivity({
      actorUserId: ctx.userId,
      type: 'marketing_attendance_check_in',
      description: `Checked in for ${today}`,
      metadata: { attendanceId: row.id, date: today, at: now.toISOString() },
    });

    return res.json({ success: true, attendance: serialize(row) });
  } catch (error) {
    console.error('Error checking in:', error);
    return res.status(500).json({ error: 'Failed to record your check-in' });
  }
};

// ─────────────────────────────────────────────────────────────────────────────
// POST /marketing/attendance/check-out
// ─────────────────────────────────────────────────────────────────────────────
export const checkOut = async (req: Request, res: Response): Promise<any> => {
  try {
    const ctx = await getSalesAuth(req);
    const today = todayYmd();

    const denial = checkWritable(ctx, ctx.userId, today, { isOverride: false });
    if (denial) return res.status(denial.status).json({ error: denial.message });

    const day = ymdToDate(today);
    const existing: any = await prisma.marketing_attendance.findUnique({
      where: { user_id_attendance_date: { user_id: ctx.userId, attendance_date: day } },
    });

    if (!existing?.check_in) {
      return res.status(409).json({ error: 'You need to check in before you can check out.' });
    }
    if (existing.check_out) {
      return res.status(409).json({ error: 'You have already checked out today.', attendance: serialize(existing) });
    }

    const now = new Date();
    // Conditional on check_out still being NULL, so two rapid clicks produce one
    // write; the DB CHECK additionally refuses a check-out before check-in.
    const { count } = await prisma.marketing_attendance.updateMany({
      where: { id: existing.id, check_out: null },
      data: { check_out: now },
    });
    if (count === 0) {
      const again: any = await prisma.marketing_attendance.findUnique({ where: { id: existing.id } });
      return res.status(409).json({ error: 'You have already checked out today.', attendance: again ? serialize(again) : undefined });
    }

    const row: any = await prisma.marketing_attendance.findUnique({ where: { id: existing.id } });

    await activityService.logActivity({
      actorUserId: ctx.userId,
      type: 'marketing_attendance_check_out',
      description: `Checked out for ${today}`,
      metadata: { attendanceId: existing.id, date: today, at: now.toISOString() },
    });

    return res.json({ success: true, attendance: serialize(row) });
  } catch (error) {
    console.error('Error checking out:', error);
    return res.status(500).json({ error: 'Failed to record your check-out' });
  }
};

// ─────────────────────────────────────────────────────────────────────────────
// GET /marketing/attendance?date= — the team's day (managers)
// ─────────────────────────────────────────────────────────────────────────────
export const getTeamAttendance = async (req: Request, res: Response): Promise<any> => {
  try {
    const ctx = await getSalesAuth(req);
    if (!canViewTeamAttendance(ctx)) {
      return res.status(403).json({ error: 'You do not have permission to view team attendance.' });
    }

    const today = todayYmd();
    const date = isYmd(req.query.date) ? String(req.query.date) : today;
    if (date > today) return res.status(400).json({ error: 'Attendance cannot be read for a future date.' });

    // The Marketing roster comes from the SAME module-scoping helper every other
    // Marketing picker uses — no hardcoded team list.
    const members = await getUsersForModule('marketing');

    const rows: any[] = await prisma.marketing_attendance.findMany({
      where: { attendance_date: ymdToDate(date), user_id: { in: members.map((m) => m.id) } },
    });
    const byUser = new Map(rows.map((r) => [r.user_id, r]));

    return res.json({
      success: true,
      today,
      date,
      canOverride: canOverrideAttendance(ctx),
      historicalEditWindowDays: HISTORICAL_EDIT_WINDOW_DAYS,
      statuses: ATTENDANCE_STATUSES.map((key) => ({ key, label: ATTENDANCE_STATUS_LABELS[key] })),
      // A member with no row is reported as the VIRTUAL default, not written.
      // The record is spread FIRST so the roster's name is appended rather than
      // clobbered; both serialize() and virtualAbsent() already carry userId.
      records: members.map((m) => ({
        ...(byUser.has(m.id) ? serialize(byUser.get(m.id)) : virtualAbsent(m.id, date)),
        userName: m.name,
      })),
    });
  } catch (error) {
    console.error('Error loading team attendance:', error);
    return res.status(500).json({ error: 'Failed to load team attendance' });
  }
};

// ─────────────────────────────────────────────────────────────────────────────
// PUT /marketing/attendance/:userId/:date — manager / admin override
// ─────────────────────────────────────────────────────────────────────────────
export const overrideAttendance = async (req: Request, res: Response): Promise<any> => {
  try {
    const ctx = await getSalesAuth(req);

    const targetUserId = intId(req.params.userId);
    const date = String(req.params.date ?? '');
    if (!targetUserId) return res.status(400).json({ error: 'Invalid member.' });

    const b = req.body ?? {};
    const reason = str(b.reason);

    // One gate for permission + scope + the mandatory reason.
    const denial = checkWritable(ctx, targetUserId, date, { isOverride: true, reason });
    if (denial) {
      return res.status(denial.status).json({
        error: denial.message,
        ...(denial.message.includes('reason') ? { fieldErrors: { reason: denial.message } } : {}),
      });
    }

    /* P2-2 — scope the target. Previously this only proved the user EXISTED, so a
     * Marketing manager could create marketing attendance rows for an HR-only or
     * deactivated user; such rows never appear in the team list (which is
     * module-scoped) and became invisible orphans.
     *
     * getUsersForModule('marketing') is the SAME authoritative roster the team
     * view renders, and it already filters status='active' — so membership and
     * active-state are one lookup, with no second roster implementation. It
     * applies to Admins too: privilege does not make an out-of-module row correct. */
    const roster = await getUsersForModule('marketing');
    const target = roster.find((m) => m.id === targetUserId);
    if (!target) {
      return res.status(404).json({
        error: 'That member is not an active member of the Marketing team.',
      });
    }

    // "On Leave" must be backed by an approved leave record.
    const resolved = await resolveStatus(str(b.status) || 'present', targetUserId, date);
    if (isDenial(resolved)) {
      return res.status(resolved.status).json({ error: resolved.message, fieldErrors: { status: resolved.message } });
    }

    const day = ymdToDate(date);
    const before: any = await prisma.marketing_attendance.findUnique({
      where: { user_id_attendance_date: { user_id: targetUserId, attendance_date: day } },
    });

    const now = new Date();
    const data = {
      status: resolved.status,
      leave_id: resolved.leaveId,
      notes: b.notes !== undefined ? (str(b.notes) || null) : (before?.notes ?? null),
      overridden_by: ctx.userId,
      overridden_at: now,
      override_reason: reason,
    };

    const row: any = await prisma.marketing_attendance.upsert({
      where: { user_id_attendance_date: { user_id: targetUserId, attendance_date: day } },
      update: data,
      create: { user_id: targetUserId, attendance_date: day, ...data },
    });

    /* Audit through the EXISTING activity log, recording the previous values as
     * well as the new ones — an override that cannot be compared to what it
     * replaced is not much of an audit trail. */
    await activityService.logActivity({
      actorUserId: ctx.userId,
      type: 'marketing_attendance_override',
      description: `Set ${target.name}'s attendance for ${date} to ${ATTENDANCE_STATUS_LABELS[resolved.status]}`,
      metadata: {
        attendanceId: row.id,
        targetUserId,
        date,
        reason,
        previous: before
          ? { status: before.status, checkIn: before.check_in, checkOut: before.check_out, notes: before.notes }
          : null,               // null = there was no record; the default Absent applied
        next: { status: resolved.status, notes: data.notes, leaveId: resolved.leaveId },
      },
    });

    return res.json({ success: true, attendance: serialize(row) });
  } catch (error) {
    console.error('Error overriding attendance:', error);
    return res.status(500).json({ error: 'Failed to update the attendance record' });
  }
};
